PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX user: <http://www.semanticweb.org/user/ontologies/2018/1#>
PREFIX : <http://www.semanticweb.org/user/ontologies/2018/1#>

INSERT {
  GRAPH user:TISSUE {
    _:idRel user:fromTF ?tf .
    _:idRel user:fromGene ?gene .
    _:idRel user:weightP ?Wp .
    _:idRel user:weightE ?We .
    _:idRel user:score ?score .
  }
}
WHERE {
  VALUES ?g1 {user:SAMPLE1}
  VALUES ?g2 {user:SAMPLE2}
  VALUES ?g3 {user:SAMPLE3}
  VALUES ?g4 {user:SAMPLE4}
  VALUES ?g5 {user:SAMPLE5}
  VALUES ?g6 {user:SAMPLE6}
  VALUES ?g7 {user:SAMPLE7}
  VALUES ?g8 {user:SAMPLE8}
  VALUES ?g9 {user:SAMPLE9}
  VALUES ?g10 {user:SAMPLE10}
  VALUES ?g11 {user:SAMPLE11}
  VALUES ?g12 {user:SAMPLE12}
  VALUES ?g13 {user:SAMPLE13}
  VALUES ?g14 {user:SAMPLE14}
  VALUES ?g15 {user:SAMPLE15}

  ?tf rdf:type user:tf .
  ?gene rdf:type user:gene .
  OPTIONAL {
    GRAPH ?g1 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP1 .
    }
  }
BIND (IF(bound(?weightP1), ?weightP1, "0.0"^^xsd:float) AS ?Wp1) .
  OPTIONAL {
    GRAPH ?g1 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE1 .
    }
  }
BIND (IF(bound(?weightE1), ?weightE1, "0.0"^^xsd:float) AS ?We1) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP2 .
    }
  }
BIND (IF(bound(?weightP2), ?weightP2, "0.0"^^xsd:float) AS ?Wp2) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE2 .
    }
  }
BIND (IF(bound(?weightE2), ?weightE2, "0.0"^^xsd:float) AS ?We2) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP3 .
    }
  }
BIND (IF(bound(?weightP3), ?weightP3, "0.0"^^xsd:float) AS ?Wp3) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE3 .
    }
  }
BIND (IF(bound(?weightE3), ?weightE3, "0.0"^^xsd:float) AS ?We3) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP4 .
    }
  }
BIND (IF(bound(?weightP4), ?weightP4, "0.0"^^xsd:float) AS ?Wp4) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE4 .
    }
  }
BIND (IF(bound(?weightE4), ?weightE4, "0.0"^^xsd:float) AS ?We4) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP5 .
    }
  }
BIND (IF(bound(?weightP5), ?weightP5, "0.0"^^xsd:float) AS ?Wp5) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE5 .
    }
  }
BIND (IF(bound(?weightE5), ?weightE5, "0.0"^^xsd:float) AS ?We5) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP6 .
    }
  }
BIND (IF(bound(?weightP6), ?weightP6, "0.0"^^xsd:float) AS ?Wp6) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE6 .
    }
  }
BIND (IF(bound(?weightE6), ?weightE6, "0.0"^^xsd:float) AS ?We6) .
  OPTIONAL {
    GRAPH ?g7 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP7 .
    }
  }
BIND (IF(bound(?weightP7), ?weightP7, "0.0"^^xsd:float) AS ?Wp7) .
  OPTIONAL {
    GRAPH ?g7 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE7 .
    }
  }
BIND (IF(bound(?weightE7), ?weightE7, "0.0"^^xsd:float) AS ?We7) .
  OPTIONAL {
    GRAPH ?g8 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP8 .
    }
  }
BIND (IF(bound(?weightP8), ?weightP8, "0.0"^^xsd:float) AS ?Wp8) .
  OPTIONAL {
    GRAPH ?g8 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE8 .
    }
  }
BIND (IF(bound(?weightE8), ?weightE8, "0.0"^^xsd:float) AS ?We8) .
  OPTIONAL {
    GRAPH ?g9 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP9 .
    }
  }
BIND (IF(bound(?weightP9), ?weightP9, "0.0"^^xsd:float) AS ?Wp9) .
  OPTIONAL {
    GRAPH ?g9 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE9 .
    }
  }
BIND (IF(bound(?weightE9), ?weightE9, "0.0"^^xsd:float) AS ?We9) .
  OPTIONAL {
    GRAPH ?g10 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP10 .
    }
  }
BIND (IF(bound(?weightP10), ?weightP10, "0.0"^^xsd:float) AS ?Wp10) .
  OPTIONAL {
    GRAPH ?g10 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE10 .
    }
  }
BIND (IF(bound(?weightE10), ?weightE10, "0.0"^^xsd:float) AS ?We10) .
  OPTIONAL {
    GRAPH ?g11 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP11 .
    }
  }
BIND (IF(bound(?weightP11), ?weightP11, "0.0"^^xsd:float) AS ?Wp11) .
  OPTIONAL {
    GRAPH ?g11 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE11 .
    }
  }
BIND (IF(bound(?weightE11), ?weightE11, "0.0"^^xsd:float) AS ?We11) .
  OPTIONAL {
    GRAPH ?g12 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP12 .
    }
  }
BIND (IF(bound(?weightP12), ?weightP12, "0.0"^^xsd:float) AS ?Wp12) .
  OPTIONAL {
    GRAPH ?g12 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE12 .
    }
  }
BIND (IF(bound(?weightE12), ?weightE12, "0.0"^^xsd:float) AS ?We12) .
  OPTIONAL {
    GRAPH ?g13 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP13 .
    }
  }
BIND (IF(bound(?weightP13), ?weightP13, "0.0"^^xsd:float) AS ?Wp13) .
  OPTIONAL {
    GRAPH ?g13 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE13 .
    }
  }
BIND (IF(bound(?weightE13), ?weightE13, "0.0"^^xsd:float) AS ?We13) .
  OPTIONAL {
    GRAPH ?g14 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP14 .
    }
  }
BIND (IF(bound(?weightP14), ?weightP14, "0.0"^^xsd:float) AS ?Wp14) .
  OPTIONAL {
    GRAPH ?g14 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE14 .
    }
  }
BIND (IF(bound(?weightE14), ?weightE14, "0.0"^^xsd:float) AS ?We14) .
  OPTIONAL {
    GRAPH ?g15 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP15 .
    }
  }
BIND (IF(bound(?weightP15), ?weightP15, "0.0"^^xsd:float) AS ?Wp15) .
  OPTIONAL {
    GRAPH ?g15 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE15 .
    }
  }
BIND (IF(bound(?weightE15), ?weightE15, "0.0"^^xsd:float) AS ?We15) .


BIND (IF((?We1 > ?We2),?We1, ?We2) AS ?WeA)
BIND (IF((?Wp1 > ?Wp2),?Wp1, ?Wp2) AS ?WpA)
BIND (IF((?WeA > ?We3),?WeA, ?We3) AS ?WeB)
BIND (IF((?WpA > ?Wp3),?WpA, ?Wp3) AS ?WpB)
BIND (IF((?WeB > ?We4),?WeB, ?We4) AS ?WeC)
BIND (IF((?WpB > ?Wp4),?WpB, ?Wp4) AS ?WpC)
BIND (IF((?WeC > ?We5),?WeC, ?We5) AS ?WeD)
BIND (IF((?WpC > ?Wp5),?WpC, ?Wp5) AS ?WpD)
BIND (IF((?WeD > ?We6),?WeD, ?We6) AS ?WeE)
BIND (IF((?WpD > ?Wp6),?WpD, ?Wp6) AS ?WpE)
BIND (IF((?WeE > ?We7),?WeE, ?We7) AS ?WeF)
BIND (IF((?WpE > ?Wp7),?WpE, ?Wp7) AS ?WpF)
BIND (IF((?WeF > ?We8),?WeF, ?We8) AS ?WeG)
BIND (IF((?WpF > ?Wp8),?WpF, ?Wp8) AS ?WpG)
BIND (IF((?WeG > ?We9),?WeG, ?We9) AS ?WeH)
BIND (IF((?WpG > ?Wp9),?WpG, ?Wp9) AS ?WpH)
BIND (IF((?WeH > ?We10),?WeH, ?We10) AS ?WeI)
BIND (IF((?WpH > ?Wp10),?WpH, ?Wp10) AS ?WpI)
BIND (IF((?WeI > ?We11),?WeI, ?We11) AS ?WeJ)
BIND (IF((?WpI > ?Wp11),?WpI, ?Wp11) AS ?WpJ)
BIND (IF((?WeJ > ?We12),?WeJ, ?We12) AS ?WeK)
BIND (IF((?WpJ > ?Wp12),?WpJ, ?Wp12) AS ?WpK)
BIND (IF((?WeK > ?We13),?WeK, ?We13) AS ?WeL)
BIND (IF((?WpK > ?Wp13),?WpK, ?Wp13) AS ?WpL)
BIND (IF((?WeL > ?We14),?WeL, ?We14) AS ?WeM)
BIND (IF((?WpL > ?Wp14),?WpL, ?Wp14) AS ?WpM)
BIND (IF((?WeM > ?We15),?WeM, ?We15) AS ?We)
BIND (IF((?WpM > ?Wp15),?WpM, ?Wp15) AS ?Wp)
BIND (IF((?We > ?Wp),?We, ?Wp) AS ?score)
FILTER (?score >0)
}
