PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rcg: <http://regulatorycircuits.org/graph/>
PREFIX rc: <http://regulatorycircuits.org/data/>

INSERT {
  GRAPH rcg:CD14+_Monocytes {
    _:idRel rc:fromTF ?tf .
    _:idRel rc:fromGene ?gene .
    _:idRel rc:weightP ?Wp .
    _:idRel rc:weightE ?We .
    _:idRel rc:score ?score .
  }
}


WHERE {
  VALUES ?g1 {rcg:CNhs10852}
  VALUES ?g2 {rcg:CNhs11954}
  VALUES ?g3 {rcg:CNhs11997}
  VALUES ?g4 {rcg:CNhs13468}
  VALUES ?g5 {rcg:CNhs13484}
  VALUES ?g6 {rcg:CNhs13491}
  VALUES ?g7 {rcg:CNhs13465}
  VALUES ?g8 {rcg:CNhs13475}
  VALUES ?g9 {rcg:CNhs13543}
  VALUES ?g10 {rcg:CNhs13474}
  VALUES ?g11 {rcg:CNhs13483}
  VALUES ?g12 {rcg:CNhs13489}
  VALUES ?g13 {rcg:CNhs13495}
  VALUES ?g14 {rcg:CNhs13473}
  VALUES ?g15 {rcg:CNhs13488}
  VALUES ?g16 {rcg:CNhs13494}
  VALUES ?g17 {rcg:CNhs13472}
  VALUES ?g18 {rcg:CNhs13487}
  VALUES ?g19 {rcg:CNhs13546}
  VALUES ?g20 {rcg:CNhs13469}
  VALUES ?g21 {rcg:CNhs13532}
  VALUES ?g22 {rcg:CNhs13492}
  VALUES ?g23 {rcg:CNhs13466}
  VALUES ?g24 {rcg:CNhs13476}
  VALUES ?g25 {rcg:CNhs13490}
  VALUES ?g26 {rcg:CNhs13470}
  VALUES ?g27 {rcg:CNhs13533}
  VALUES ?g28 {rcg:CNhs13545}
  VALUES ?g29 {rcg:CNhs13471}
  VALUES ?g30 {rcg:CNhs13485}
  VALUES ?g31 {rcg:CNhs13493}
  VALUES ?g32 {rcg:CNhs13467}
  VALUES ?g33 {rcg:CNhs13544}

  ?tf rdf:type rc:tf .
  ?gene rdf:type rc:gene .
  OPTIONAL {
    GRAPH ?g1 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP1 .
    }
  }
BIND (IF(bound(?weightP1), ?weightP1, "0.0"^^xsd:float) AS ?Wp1) .
  OPTIONAL {
    GRAPH ?g1 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE1 .
    }
  }
BIND (IF(bound(?weightE1), ?weightE1, "0.0"^^xsd:float) AS ?We1) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP2 .
    }
  }
BIND (IF(bound(?weightP2), ?weightP2, "0.0"^^xsd:float) AS ?Wp2) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE2 .
    }
  }
BIND (IF(bound(?weightE2), ?weightE2, "0.0"^^xsd:float) AS ?We2) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP3 .
    }
  }
BIND (IF(bound(?weightP3), ?weightP3, "0.0"^^xsd:float) AS ?Wp3) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE3 .
    }
  }
BIND (IF(bound(?weightE3), ?weightE3, "0.0"^^xsd:float) AS ?We3) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP4 .
    }
  }
BIND (IF(bound(?weightP4), ?weightP4, "0.0"^^xsd:float) AS ?Wp4) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE4 .
    }
  }
BIND (IF(bound(?weightE4), ?weightE4, "0.0"^^xsd:float) AS ?We4) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP5 .
    }
  }
BIND (IF(bound(?weightP5), ?weightP5, "0.0"^^xsd:float) AS ?Wp5) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE5 .
    }
  }
BIND (IF(bound(?weightE5), ?weightE5, "0.0"^^xsd:float) AS ?We5) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP6 .
    }
  }
BIND (IF(bound(?weightP6), ?weightP6, "0.0"^^xsd:float) AS ?Wp6) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE6 .
    }
  }
BIND (IF(bound(?weightE6), ?weightE6, "0.0"^^xsd:float) AS ?We6) .
  OPTIONAL {
    GRAPH ?g7 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP7 .
    }
  }
BIND (IF(bound(?weightP7), ?weightP7, "0.0"^^xsd:float) AS ?Wp7) .
  OPTIONAL {
    GRAPH ?g7 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE7 .
    }
  }
BIND (IF(bound(?weightE7), ?weightE7, "0.0"^^xsd:float) AS ?We7) .
  OPTIONAL {
    GRAPH ?g8 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP8 .
    }
  }
BIND (IF(bound(?weightP8), ?weightP8, "0.0"^^xsd:float) AS ?Wp8) .
  OPTIONAL {
    GRAPH ?g8 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE8 .
    }
  }
BIND (IF(bound(?weightE8), ?weightE8, "0.0"^^xsd:float) AS ?We8) .
  OPTIONAL {
    GRAPH ?g9 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP9 .
    }
  }
BIND (IF(bound(?weightP9), ?weightP9, "0.0"^^xsd:float) AS ?Wp9) .
  OPTIONAL {
    GRAPH ?g9 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE9 .
    }
  }
BIND (IF(bound(?weightE9), ?weightE9, "0.0"^^xsd:float) AS ?We9) .
  OPTIONAL {
    GRAPH ?g10 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP10 .
    }
  }
BIND (IF(bound(?weightP10), ?weightP10, "0.0"^^xsd:float) AS ?Wp10) .
  OPTIONAL {
    GRAPH ?g10 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE10 .
    }
  }
BIND (IF(bound(?weightE10), ?weightE10, "0.0"^^xsd:float) AS ?We10) .
  OPTIONAL {
    GRAPH ?g11 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP11 .
    }
  }
BIND (IF(bound(?weightP11), ?weightP11, "0.0"^^xsd:float) AS ?Wp11) .
  OPTIONAL {
    GRAPH ?g11 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE11 .
    }
  }
BIND (IF(bound(?weightE11), ?weightE11, "0.0"^^xsd:float) AS ?We11) .
  OPTIONAL {
    GRAPH ?g12 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP12 .
    }
  }
BIND (IF(bound(?weightP12), ?weightP12, "0.0"^^xsd:float) AS ?Wp12) .
  OPTIONAL {
    GRAPH ?g12 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE12 .
    }
  }
BIND (IF(bound(?weightE12), ?weightE12, "0.0"^^xsd:float) AS ?We12) .
  OPTIONAL {
    GRAPH ?g13 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP13 .
    }
  }
BIND (IF(bound(?weightP13), ?weightP13, "0.0"^^xsd:float) AS ?Wp13) .
  OPTIONAL {
    GRAPH ?g13 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE13 .
    }
  }
BIND (IF(bound(?weightE13), ?weightE13, "0.0"^^xsd:float) AS ?We13) .
  OPTIONAL {
    GRAPH ?g14 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP14 .
    }
  }
BIND (IF(bound(?weightP14), ?weightP14, "0.0"^^xsd:float) AS ?Wp14) .
  OPTIONAL {
    GRAPH ?g14 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE14 .
    }
  }
BIND (IF(bound(?weightE14), ?weightE14, "0.0"^^xsd:float) AS ?We14) .
  OPTIONAL {
    GRAPH ?g15 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP15 .
    }
  }
BIND (IF(bound(?weightP15), ?weightP15, "0.0"^^xsd:float) AS ?Wp15) .
  OPTIONAL {
    GRAPH ?g15 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE15 .
    }
  }
BIND (IF(bound(?weightE15), ?weightE15, "0.0"^^xsd:float) AS ?We15) .
  OPTIONAL {
    GRAPH ?g16 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP16 .
    }
  }
BIND (IF(bound(?weightP16), ?weightP16, "0.0"^^xsd:float) AS ?Wp16) .
  OPTIONAL {
    GRAPH ?g16 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE16 .
    }
  }
BIND (IF(bound(?weightE16), ?weightE16, "0.0"^^xsd:float) AS ?We16) .
  OPTIONAL {
    GRAPH ?g17 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP17 .
    }
  }
BIND (IF(bound(?weightP17), ?weightP17, "0.0"^^xsd:float) AS ?Wp17) .
  OPTIONAL {
    GRAPH ?g17 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE17 .
    }
  }
BIND (IF(bound(?weightE17), ?weightE17, "0.0"^^xsd:float) AS ?We17) .
  OPTIONAL {
    GRAPH ?g18 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP18 .
    }
  }
BIND (IF(bound(?weightP18), ?weightP18, "0.0"^^xsd:float) AS ?Wp18) .
  OPTIONAL {
    GRAPH ?g18 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE18 .
    }
  }
BIND (IF(bound(?weightE18), ?weightE18, "0.0"^^xsd:float) AS ?We18) .
  OPTIONAL {
    GRAPH ?g19 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP19 .
    }
  }
BIND (IF(bound(?weightP19), ?weightP19, "0.0"^^xsd:float) AS ?Wp19) .
  OPTIONAL {
    GRAPH ?g19 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE19 .
    }
  }
BIND (IF(bound(?weightE19), ?weightE19, "0.0"^^xsd:float) AS ?We19) .
  OPTIONAL {
    GRAPH ?g20 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP20 .
    }
  }
BIND (IF(bound(?weightP20), ?weightP20, "0.0"^^xsd:float) AS ?Wp20) .
  OPTIONAL {
    GRAPH ?g20 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE20 .
    }
  }
BIND (IF(bound(?weightE20), ?weightE20, "0.0"^^xsd:float) AS ?We20) .
  OPTIONAL {
    GRAPH ?g21 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP21 .
    }
  }
BIND (IF(bound(?weightP21), ?weightP21, "0.0"^^xsd:float) AS ?Wp21) .
  OPTIONAL {
    GRAPH ?g21 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE21 .
    }
  }
BIND (IF(bound(?weightE21), ?weightE21, "0.0"^^xsd:float) AS ?We21) .
  OPTIONAL {
    GRAPH ?g22 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP22 .
    }
  }
BIND (IF(bound(?weightP22), ?weightP22, "0.0"^^xsd:float) AS ?Wp22) .
  OPTIONAL {
    GRAPH ?g22 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE22 .
    }
  }
BIND (IF(bound(?weightE22), ?weightE22, "0.0"^^xsd:float) AS ?We22) .
  OPTIONAL {
    GRAPH ?g23 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP23 .
    }
  }
BIND (IF(bound(?weightP23), ?weightP23, "0.0"^^xsd:float) AS ?Wp23) .
  OPTIONAL {
    GRAPH ?g23 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE23 .
    }
  }
BIND (IF(bound(?weightE23), ?weightE23, "0.0"^^xsd:float) AS ?We23) .
  OPTIONAL {
    GRAPH ?g24 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP24 .
    }
  }
BIND (IF(bound(?weightP24), ?weightP24, "0.0"^^xsd:float) AS ?Wp24) .
  OPTIONAL {
    GRAPH ?g24 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE24 .
    }
  }
BIND (IF(bound(?weightE24), ?weightE24, "0.0"^^xsd:float) AS ?We24) .
  OPTIONAL {
    GRAPH ?g25 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP25 .
    }
  }
BIND (IF(bound(?weightP25), ?weightP25, "0.0"^^xsd:float) AS ?Wp25) .
  OPTIONAL {
    GRAPH ?g25 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE25 .
    }
  }
BIND (IF(bound(?weightE25), ?weightE25, "0.0"^^xsd:float) AS ?We25) .
  OPTIONAL {
    GRAPH ?g26 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP26 .
    }
  }
BIND (IF(bound(?weightP26), ?weightP26, "0.0"^^xsd:float) AS ?Wp26) .
  OPTIONAL {
    GRAPH ?g26 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE26 .
    }
  }
BIND (IF(bound(?weightE26), ?weightE26, "0.0"^^xsd:float) AS ?We26) .
  OPTIONAL {
    GRAPH ?g27 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP27 .
    }
  }
BIND (IF(bound(?weightP27), ?weightP27, "0.0"^^xsd:float) AS ?Wp27) .
  OPTIONAL {
    GRAPH ?g27 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE27 .
    }
  }
BIND (IF(bound(?weightE27), ?weightE27, "0.0"^^xsd:float) AS ?We27) .
  OPTIONAL {
    GRAPH ?g28 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP28 .
    }
  }
BIND (IF(bound(?weightP28), ?weightP28, "0.0"^^xsd:float) AS ?Wp28) .
  OPTIONAL {
    GRAPH ?g28 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE28 .
    }
  }
BIND (IF(bound(?weightE28), ?weightE28, "0.0"^^xsd:float) AS ?We28) .
  OPTIONAL {
    GRAPH ?g29 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP29 .
    }
  }
BIND (IF(bound(?weightP29), ?weightP29, "0.0"^^xsd:float) AS ?Wp29) .
  OPTIONAL {
    GRAPH ?g29 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE29 .
    }
  }
BIND (IF(bound(?weightE29), ?weightE29, "0.0"^^xsd:float) AS ?We29) .
  OPTIONAL {
    GRAPH ?g30 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP30 .
    }
  }
BIND (IF(bound(?weightP30), ?weightP30, "0.0"^^xsd:float) AS ?Wp30) .
  OPTIONAL {
    GRAPH ?g30 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE30 .
    }
  }
BIND (IF(bound(?weightE30), ?weightE30, "0.0"^^xsd:float) AS ?We30) .
  OPTIONAL {
    GRAPH ?g31 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP31 .
    }
  }
BIND (IF(bound(?weightP31), ?weightP31, "0.0"^^xsd:float) AS ?Wp31) .
  OPTIONAL {
    GRAPH ?g31 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE31 .
    }
  }
BIND (IF(bound(?weightE31), ?weightE31, "0.0"^^xsd:float) AS ?We31) .
  OPTIONAL {
    GRAPH ?g32 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP32 .
    }
  }
BIND (IF(bound(?weightP32), ?weightP32, "0.0"^^xsd:float) AS ?Wp32) .
  OPTIONAL {
    GRAPH ?g32 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE32 .
    }
  }
BIND (IF(bound(?weightE32), ?weightE32, "0.0"^^xsd:float) AS ?We32) .
  OPTIONAL {
    GRAPH ?g33 {
      ?rP rc:fromTF ?tf.
      ?rP rc:fromGene ?gene .
      ?rP rc:weightP ?weightP33 .
    }
  }
BIND (IF(bound(?weightP33), ?weightP33, "0.0"^^xsd:float) AS ?Wp33) .
  OPTIONAL {
    GRAPH ?g33 {
      ?rE rc:fromTF ?tf.
      ?rE rc:fromGene ?gene .
      ?rE rc:weightE ?weightE33 .
    }
  }
BIND (IF(bound(?weightE33), ?weightE33, "0.0"^^xsd:float) AS ?We33) .


BIND (IF((?We1 > ?We2),?We1, ?We2) AS ?WeA)
BIND (IF((?Wp1 > ?Wp2),?Wp1, ?Wp2) AS ?WpA)
BIND (IF((?WeA > ?We3),?WeA, ?We3) AS ?WeB)
BIND (IF((?WpA > ?Wp3),?WpA, ?Wp3) AS ?WpB)
BIND (IF((?WeB > ?We4),?WeB, ?We4) AS ?WeC)
BIND (IF((?WpB > ?Wp4),?WpB, ?Wp4) AS ?WpC)
BIND (IF((?WeC > ?We5),?WeC, ?We5) AS ?WeD)
BIND (IF((?WpC > ?Wp5),?WpC, ?Wp5) AS ?WpD)
BIND (IF((?WeD > ?We6),?WeD, ?We6) AS ?WeE)
BIND (IF((?WpD > ?Wp6),?WpD, ?Wp6) AS ?WpE)
BIND (IF((?WeE > ?We7),?WeE, ?We7) AS ?WeF)
BIND (IF((?WpE > ?Wp7),?WpE, ?Wp7) AS ?WpF)
BIND (IF((?WeF > ?We8),?WeF, ?We8) AS ?WeG)
BIND (IF((?WpF > ?Wp8),?WpF, ?Wp8) AS ?WpG)
BIND (IF((?WeG > ?We9),?WeG, ?We9) AS ?WeH)
BIND (IF((?WpG > ?Wp9),?WpG, ?Wp9) AS ?WpH)
BIND (IF((?WeH > ?We10),?WeH, ?We10) AS ?WeI)
BIND (IF((?WpH > ?Wp10),?WpH, ?Wp10) AS ?WpI)
BIND (IF((?WeI > ?We11),?WeI, ?We11) AS ?WeJ)
BIND (IF((?WpI > ?Wp11),?WpI, ?Wp11) AS ?WpJ)
BIND (IF((?WeJ > ?We12),?WeJ, ?We12) AS ?WeK)
BIND (IF((?WpJ > ?Wp12),?WpJ, ?Wp12) AS ?WpK)
BIND (IF((?WeK > ?We13),?WeK, ?We13) AS ?WeL)
BIND (IF((?WpK > ?Wp13),?WpK, ?Wp13) AS ?WpL)
BIND (IF((?WeL > ?We14),?WeL, ?We14) AS ?WeM)
BIND (IF((?WpL > ?Wp14),?WpL, ?Wp14) AS ?WpM)
BIND (IF((?WeM > ?We15),?WeM, ?We15) AS ?WeN)
BIND (IF((?WpM > ?Wp15),?WpM, ?Wp15) AS ?WpN)
BIND (IF((?WeN > ?We16),?WeN, ?We16) AS ?WeO)
BIND (IF((?WpN > ?Wp16),?WpN, ?Wp16) AS ?WpO)
BIND (IF((?WeO > ?We17),?WeO, ?We17) AS ?WeP)
BIND (IF((?WpO > ?Wp17),?WpO, ?Wp17) AS ?WpP)
BIND (IF((?WeP > ?We18),?WeP, ?We18) AS ?WeR)
BIND (IF((?WpP > ?Wp18),?WpP, ?Wp18) AS ?WpR)
BIND (IF((?WeR > ?We19),?WeR, ?We19) AS ?WeS)
BIND (IF((?WpR > ?Wp19),?WpR, ?Wp19) AS ?WpS)
BIND (IF((?WeS > ?We20),?WeS, ?We20) AS ?WeT)
BIND (IF((?WpS > ?Wp20),?WpS, ?Wp20) AS ?WpT)
BIND (IF((?WeT > ?We21),?WeT, ?We21) AS ?WeU)
BIND (IF((?WpT > ?Wp21),?WpT, ?Wp21) AS ?WpU)
BIND (IF((?WeU > ?We22),?WeU, ?We22) AS ?WeV)
BIND (IF((?WpU > ?Wp22),?WpU, ?Wp22) AS ?WpV)
BIND (IF((?WeV > ?We23),?WeV, ?We23) AS ?WeW)
BIND (IF((?WpV > ?Wp23),?WpV, ?Wp23) AS ?WpW)
BIND (IF((?WeW > ?We24),?WeW, ?We24) AS ?WeX)
BIND (IF((?WpW > ?Wp24),?WpW, ?Wp24) AS ?WpX)
BIND (IF((?WeX > ?We25),?WeX, ?We25) AS ?WeY)
BIND (IF((?WpX > ?Wp25),?WpX, ?Wp25) AS ?WpY)
BIND (IF((?WeY > ?We26),?WeY, ?We26) AS ?WeZ)
BIND (IF((?WpY > ?Wp26),?WpY, ?Wp26) AS ?WpZ)
BIND (IF((?WeZ > ?We27),?WeZ, ?We27) AS ?WeA1)
BIND (IF((?WpZ > ?Wp27),?WpZ, ?Wp27) AS ?WpA1)
BIND (IF((?WeA1 > ?We28),?WeA1, ?We28) AS ?WeA2)
BIND (IF((?WpA1 > ?Wp28),?WpA1, ?Wp28) AS ?WpA2)
BIND (IF((?WeA2 > ?We29),?WeA2, ?We29) AS ?WeA3)
BIND (IF((?WpA2 > ?Wp29),?WpA2, ?Wp29) AS ?WpA3)
BIND (IF((?WeA3 > ?We30),?WeA3, ?We30) AS ?WeA4)
BIND (IF((?WpA3 > ?Wp30),?WpA3, ?Wp30) AS ?WpA4)
BIND (IF((?WeA4 > ?We31),?WeA4, ?We31) AS ?WeA5)
BIND (IF((?WpA4 > ?Wp31),?WpA4, ?Wp31) AS ?WpA5)
BIND (IF((?WeA5 > ?We32),?WeA5, ?We32) AS ?WeA6)
BIND (IF((?WpA5 > ?Wp32),?WpA5, ?Wp32) AS ?WpA6)
BIND (IF((?WeA6 > ?We33),?WeA6, ?We33) AS ?We)
BIND (IF((?WpA6 > ?Wp33),?WpA6, ?Wp33) AS ?Wp)
BIND (IF((?We > ?Wp),?We, ?Wp) AS ?score)
FILTER (?score >0)
}
