PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX user: <http://www.semanticweb.org/user/ontologies/2018/1#>
PREFIX : <http://www.semanticweb.org/user/ontologies/2018/1#>

INSERT {
  GRAPH user:TISSUE {
    _:idRel user:fromTF ?tf .
    _:idRel user:fromGene ?gene .
    _:idRel user:weightP ?Wp .
    _:idRel user:weightE ?We .
    _:idRel user:score ?score .
  }
}
WHERE {
  VALUES ?g1 {user:SAMPLE1}
  VALUES ?g2 {user:SAMPLE2}
  VALUES ?g3 {user:SAMPLE3}
  VALUES ?g4 {user:SAMPLE4}
  VALUES ?g5 {user:SAMPLE5}
  VALUES ?g6 {user:SAMPLE6}
  ?tf rdf:type user:tf .
  ?gene rdf:type user:gene .
  OPTIONAL {
    GRAPH ?g1 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP1 .
    }
  }
BIND (IF(bound(?weightP1), ?weightP1, "0.0"^^xsd:float) AS ?Wp1) .
  OPTIONAL {
    GRAPH ?g1 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE1 .
    }
  }
BIND (IF(bound(?weightE1), ?weightE1, "0.0"^^xsd:float) AS ?We1) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP2 .
    }
  }
BIND (IF(bound(?weightP2), ?weightP2, "0.0"^^xsd:float) AS ?Wp2) .
  OPTIONAL {
    GRAPH ?g2 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE2 .
    }
  }
BIND (IF(bound(?weightE2), ?weightE2, "0.0"^^xsd:float) AS ?We2) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP3 .
    }
  }
BIND (IF(bound(?weightP3), ?weightP3, "0.0"^^xsd:float) AS ?Wp3) .
  OPTIONAL {
    GRAPH ?g3 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE3 .
    }
  }
BIND (IF(bound(?weightE3), ?weightE3, "0.0"^^xsd:float) AS ?We3) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP4 .
    }
  }
BIND (IF(bound(?weightP4), ?weightP4, "0.0"^^xsd:float) AS ?Wp4) .
  OPTIONAL {
    GRAPH ?g4 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE4 .
    }
  }
BIND (IF(bound(?weightE4), ?weightE4, "0.0"^^xsd:float) AS ?We4) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP5 .
    }
  }
BIND (IF(bound(?weightP5), ?weightP5, "0.0"^^xsd:float) AS ?Wp5) .
  OPTIONAL {
    GRAPH ?g5 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE5 .
    }
  }
BIND (IF(bound(?weightE5), ?weightE5, "0.0"^^xsd:float) AS ?We5) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rP user:fromTF ?tf.
      ?rP user:fromGene ?gene .
      ?rP user:weightP ?weightP6 .
    }
  }
BIND (IF(bound(?weightP6), ?weightP6, "0.0"^^xsd:float) AS ?Wp6) .
  OPTIONAL {
    GRAPH ?g6 {
      ?rE user:fromTF ?tf.
      ?rE user:fromGene ?gene .
      ?rE user:weightE ?weightE6 .
    }
  }
BIND (IF(bound(?weightE6), ?weightE6, "0.0"^^xsd:float) AS ?We6) .

BIND (IF((?We1 > ?We2),?We1, ?We2) AS ?WeA)
BIND (IF((?Wp1 > ?Wp2),?Wp1, ?Wp2) AS ?WpA)
BIND (IF((?WeA > ?We3),?WeA, ?We3) AS ?WeB)
BIND (IF((?WpA > ?Wp3),?WpA, ?Wp3) AS ?WpB)
BIND (IF((?WeB > ?We4),?WeB, ?We4) AS ?WeC)
BIND (IF((?WpB > ?Wp4),?WpB, ?Wp4) AS ?WpC)
BIND (IF((?WeC > ?We5),?WeC, ?We5) AS ?WeD)
BIND (IF((?WpC > ?Wp5),?WpC, ?Wp5) AS ?WpD)
BIND (IF((?WeD > ?We6),?WeD, ?We6) AS ?We)
BIND (IF((?WpD > ?Wp6),?WpD, ?Wp6) AS ?Wp)
BIND (IF((?We > ?Wp),?We, ?Wp) AS ?score)
FILTER (?score >0)
}
