PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bfo: <http://purl.obolibrary.org/obo/BFO_> # bfo:0000050 = part_of

PREFIX fma: <http://purl.org/sig/ont/fma/>

SELECT ?anatomicalStruct 
WHERE {
  VALUES ?labelRel { rdfs:label fma:synonym }

  ?anatomicalStruct ?labelRel ?anatomicalLabel .
  FILTER(lcase(str(?anatomicalLabel)) = "ReplaceByAnatomicalName")
}
