PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX user: <http://regulatorycircuits.org/data/>
PREFIX graph: <http://regulatorycircuits.org/graph/>
PREFIX rco: <http://regulatorycircuits.org/data/>

FROM graph:experimentalContext

INSERT {
  GRAPH graph:experimentalContext {
    rc:myTissue rdf:type rco:TissueSpecificCircuit .
    rc:myTissue rco:isComposedOf ?sample .
  }
}
WHERE {
  rc:TISSUE rco:isComposedOf ?sample .
  ?sample rc:tissue rc:blood .
  ?sample rc:patient [ rc:gender pato:Male ;
                       rc:age ?age ] .
  FILTER ( ?age > "55"^^xsd:integer)
  
}
