#This query lists all the samples composing one biological tissue that are linked to a disease

prefix rc: <http://regulatorycircuits.org/data/>
prefix rcg: <http://regulatorycircuits.org/graph/>
prefix rco: <http://regulatorycircuits.org/ontology/>

SELECT DISTINCT ?sample ?diseaseName
WHERE {
  ?sample rco:sampleInTissue rc:blood . #blood can be change to any other biological tissue or this line can be removed for broader results
  ?sample rco:isDisease ?disease .
  FILTER ( ?disease = "true") #chqnge for false to get healthy samples
  ?sample rco:DiseaseName ?diseaseName .
}
