FROM graph:experimentalContext

INSERT {
  GRAPH graph:experimentalContext {
    rc:myTissue rdf:type rco:TissueSpecificCircuit .
    rc:myTissue rco:isComposedOf ?sample .
  }
}
WHERE {
  rc:CD14%2B%20Monocytes rco:isComposedOf ?sample .
  ?sample rc:tissue rc:blood .
  ?sample rc:patient [ rc:gender pato:Male ;
                       rc:age ?age ] .
  FILTER ( ?age > "55"^^xsd:integer)
  
}
