#Extract the samples corresponding to a specific tissue or to all the tissues

prefix rc: <http://regulatorycircuits.org/data/>
prefix rcg: <http://regulatorycircuits.org/graph/>
prefix rco: <http://regulatorycircuits.org/ontology/>

SELECT DISTINCT ?tissue ?sample
WHERE {
  ?tissue rco:tissueComposedOf ?sample . #To search a sigular Tissue change "?tissue" to rc:NAME_TISSUE here and remove it from the SELECT line
}
