PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX user: <http://www.semanticweb.org/user/ontologies/2018/1#>
PREFIX : <http://www.semanticweb.org/user/ontologies/2018/1#>


INSERT {
  GRAPH user:SAMPLE {
    _:idRel user:fromTF ?tf_uri .
    _:idRel user:fromGene ?gene_uri .
    _:idRel user:weightE ?max_weightE .
  }
}


WHERE {
SELECT ?tf_uri ?gene_uri (max (?weightE) AS ?max_weightE)
WHERE {
    ?tf_uri user:inclu ?tf_enhancer_uri .
    ?enhancer_uri user:in ?tf_enhancer_uri .
    ?enhancer_uri user:nextto ?enhancer_transcript_uri .
    ?transcript_uri user:nextto ?enhancer_transcript_uri .
    ?transcript_uri user:istranscript ?transcript_gene_uri .
    ?gene_uri user:isgene ?transcript_gene_uri .
    ?tf_uri rdf:type user:tf .
    ?tf_uri rdfs:label ?tf_Label .
    ?tf_enhancer_uri rdf:type user:tf_enhancer .
    ?tf_enhancer_uri rdfs:label ?tf_enhancer_Label .
    ?tf_enhancer_uri user:confidence ?tf_enhancer_confidence .
    ?enhancer_uri rdf:type user:enhancer .
    ?enhancer_uri rdfs:label ?enhancer_Label .
    ?enhancer_uri user:SAMPLE ?enhancer_SAMPLE .
    ?enhancer_transcript_uri rdf:type user:enhancer_transcript .
    ?enhancer_transcript_uri rdfs:label ?enhancer_transcript_Label .
    ?enhancer_transcript_uri user:weight ?enhancer_transcript_weight .
    ?transcript_uri rdf:type user:transcript .
    ?transcript_uri rdfs:label ?transcript_Label .
    ?transcript_uri user:SAMPLE ?transcript_SAMPLE .
    ?transcript_gene_uri rdf:type user:transcript_gene .
    ?transcript_gene_uri rdfs:label ?transcript_gene_Label .
    ?gene_uri rdf:type user:gene .
    ?gene_uri rdfs:label ?gene_Label .
    BIND (xsd:float(?tf_enhancer_confidence) * xsd:float(?tf_enhancer_confidence) * xsd:float(?enhancer_transcript_weight) * xsd:float(?enhancer_transcript_weight) * xsd:float(?transcript_SAMPLE) * xsd:float(?enhancer_SAMPLE) AS ?weightE)
    FILTER ( ?weightE > 0 )
}
}
