PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rcg: <http://regulatorycircuits.org/graph/>
PREFIX rc: <http://regulatorycircuits.org/data/>


INSERT {
  GRAPH rcg:SAMPLE {
    _:idRel rc:fromTF ?tf_uri .
    _:idRel rc:fromGene ?gene_uri .
    _:idRel rc:weightE ?max_weightE .
  }
}


WHERE {
SELECT ?tf_uri ?gene_uri (max (?weightE) AS ?max_weightE)
WHERE {
    ?tf_uri rc:inclu ?tf_enhancer_uri .
    ?enhancer_uri rc:in ?tf_enhancer_uri .
    ?enhancer_uri rc:nextto ?enhancer_transcript_uri .
    ?transcript_uri rc:nextto ?enhancer_transcript_uri .
    ?transcript_uri rc:istranscript ?transcript_gene_uri .
    ?gene_uri rc:isgene ?transcript_gene_uri .
    ?tf_uri rdf:type rc:tf .
    ?tf_uri rdfs:label ?tf_Label .
    ?tf_enhancer_uri rdf:type rc:tf_enhancer .
    ?tf_enhancer_uri rdfs:label ?tf_enhancer_Label .
    ?tf_enhancer_uri rc:confidence ?tf_enhancer_confidence .
    ?enhancer_uri rdf:type rc:enhancer .
    ?enhancer_uri rdfs:label ?enhancer_Label .
    ?enhancer_uri rc:SAMPLE ?enhancer_SAMPLE .
    ?enhancer_transcript_uri rdf:type rc:enhancer_transcript .
    ?enhancer_transcript_uri rdfs:label ?enhancer_transcript_Label .
    ?enhancer_transcript_uri rc:weight ?enhancer_transcript_weight .
    ?transcript_uri rdf:type rc:transcript .
    ?transcript_uri rdfs:label ?transcript_Label .
    ?transcript_uri rc:SAMPLE ?transcript_SAMPLE .
    ?transcript_gene_uri rdf:type rc:transcript_gene .
    ?transcript_gene_uri rdfs:label ?transcript_gene_Label .
    ?gene_uri rdf:type rc:gene .
    ?gene_uri rdfs:label ?gene_Label .
    BIND (xsd:float(?tf_enhancer_confidence) * xsd:float(?tf_enhancer_confidence) * xsd:float(?enhancer_transcript_weight) * xsd:float(?enhancer_transcript_weight) * xsd:float(?transcript_SAMPLE) * xsd:float(?enhancer_SAMPLE) AS ?weightE)
    FILTER ( ?weightE > 0 )
}
}
