PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rcg: <http://regulatorycircuits.org/graph/>
PREFIX rc: <http://regulatorycircuits.org/data/>


INSERT {
  GRAPH rcg:SAMPLE {
    _:idRel rc:fromTF ?tf_uri .
    _:idRel rc:fromGene ?gene_uri .
    _:idRel rc:weightP ?max_weightP .
  }
}


WHERE {
SELECT ?tf_uri ?gene_uri (max (?weightP) AS ?max_weightP)
WHERE {
    ?tf_uri rc:inclu ?tf_promoter_uri .
    ?tf_promoter_uri rc:in ?promoter_uri .
    ?promoter_transcript_uri rc:nextto ?promoter_uri .
    ?transcript_uri rc:nextto ?promoter_transcript_uri .
    ?transcript_gene_uri rc:istranscript ?transcript_uri .
    ?gene_uri rc:isgene ?transcript_gene_uri .
    ?tf_uri rdf:type rc:tf .
    ?tf_uri rdfs:label ?tf_Label .
    ?tf_promoter_uri rdf:type rc:tf_promoter .
    ?tf_promoter_uri rdfs:label ?tf_promoter_Label .
    ?tf_promoter_uri rc:confidence ?tf_promoter_confidence .
    ?promoter_uri rdf:type rc:promoter .
    ?promoter_uri rdfs:label ?promoter_Label .
    ?promoter_uri rc:SAMPLE ?promoter_SAMPLE .
    ?promoter_transcript_uri rdf:type rc:promoter_transcript .
    ?promoter_transcript_uri rdfs:label ?promoter_transcript_Label .
    ?transcript_uri rdf:type rc:transcript .
    ?transcript_uri rdfs:label ?transcript_Label .
    ?transcript_uri rc:SAMPLE ?transcript_SAMPLE .
    ?transcript_gene_uri rdf:type rc:transcript_gene .
    ?transcript_gene_uri rdfs:label ?transcript_gene_Label .
    ?gene_uri rdf:type rc:gene .
    ?gene_uri rdfs:label ?gene_Label .
    BIND (xsd:float(?tf_promoter_confidence) * xsd:float(?tf_promoter_confidence) * xsd:float(?promoter_SAMPLE) * xsd:float(?promoter_SAMPLE) AS ?weightP).
    FILTER ( ?weightP > 0 )
}
}
